substitutions:
  devicename: Licht_01

esphome:
  name: licht_01
  platform: ESP8266
  board: esp01_1m

  #Correct white on boot
  on_boot:
    priority: 700.0
    then:
      - light.turn_on: 
          id: licht01
          color_temperature: 2700K

wifi:
#  use_address: lampe-abstellkammer.fritz.box
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot Licht01"
    password: !secret wifi_password
    
# Enable logging to ESPHome
logger:
  # Disable logging to serial
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret api_password

# Setup OTA password
ota:
  password: !secret ota_password

captive_portal:

output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_component2
    pin: GPIO12

light:
  - platform: cwww
    name: "Licht 01"
    cold_white: output_component1
    warm_white: output_component2
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    id: licht01
