substitutions:
  friendly_name: E14 LED 1

esphome:
  name: e14led
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
#   use_address: shelly1_1.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot E1401"
    password: !secret fallback_password 

captive_portal:

# Enable logging to ESPHome
logger:
  # Disable logging to serial
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret api_password

# Setup OTA password
ota:
  password: !secret ota_password


my9231:
 data_pin: GPIO13  
 clock_pin: GPIO15  
 num_channels: 6
 num_chips: 2 
 
output:
  - platform: my9231
    id: output_blue
    channel: 1
  - platform: my9231
    id: output_red
    channel: 3
  - platform: my9231
    id: output_green
    channel: 2
  - platform: my9231
    id: output_cold_white
    channel: 4


light:
  - platform: rgbw
    name: "E14 LED 1"
    default_transition_length: 0s
    red: output_red
    green: output_green
    blue: output_blue
    white: output_cold_white
